# Generated by Django 6.0.6 on 2026-06-27 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('yodlee_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('yodlee_access_token', models.TextField(blank=True, null=True)),
                ('yodlee_token_expires', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaaSVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('aliases', models.JSONField(default=list, help_text='Alternative merchant strings that map to this vendor')),
                ('category', models.CharField(choices=[('productivity', 'Productivity'), ('communication', 'Communication'), ('development', 'Development'), ('design', 'Design'), ('marketing', 'Marketing'), ('analytics', 'Analytics'), ('security', 'Security'), ('cloud', 'Cloud Infrastructure'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('other', 'Other')], max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('avg_monthly_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SaaS Vendor',
                'verbose_name_plural': 'SaaS Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit Card'), ('business', 'Business')], max_length=50)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('yodlee_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_description', models.CharField(max_length=255)),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('first_seen', models.DateField()),
                ('last_seen', models.DateField()),
                ('next_renewal', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged'), ('duplicate', 'Duplicate'), ('orphaned', 'Orphaned'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('flag_reason', models.TextField(blank=True)),
                ('estimated_annual_waste', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.organization')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.saasvendor')),
            ],
            options={
                'ordering': ['-monthly_cost'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_description', models.TextField(help_text='Original messy merchant string from bank feed')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('transaction_date', models.DateField()),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_saas', models.BooleanField(default=False)),
                ('yodlee_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.bankaccount')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
